### ISSUE TITLE
Reconciller doesn't support systems and domains

### ISSUE THREAD

**Issue by MarcinGinszt** [OpsLevel/kubectl-opslevel#171]
Reconciller should be able to reconcile system/ domain information using Kubernetes annotations. 
This should be enabled by existing mutations (`domainChildAssign` and `systemChildAssign`).

If there is no objections, I'll prepare PR with this change

**Comment by rocktavious** [comment]
Hey @MarcinGinszt -  I have no objections if you'd like to try adding this change but I do know that this repo is quite out of date when it comes to opslevel-go's latest version and doing that update is a significant amount of work.  Additionally internally we are looking at doing a full rewrite of the architecture of this tool because we are changing how the app handles integrations like this to build out a more unified data ingestion pipeline.

I have no idea when all of the above would land or come true which is why we have deprioritzed changes to this tool temporarily (because of the architecture rewrite)

If you think you can make something work in the meantime i'm happy to review and test it.

**Comment by MarcinGinszt** [comment]
Hey @rocktavious ! 
Could you maybe give us any timeframe, when could you pick those up?

**Comment by rocktavious** [comment]
https://github.com/OpsLevel/kubectl-opslevel/pull/173#issuecomment-1724246072

**Comment by rocktavious** [comment]
@MarcinGinszt 
We have refactored a chunk of this repo out to a new library (so we can use it elsewhere) but i've added the ability to specify a system in the configuration now see here for an example - https://github.com/OpsLevel/opslevel-jq-parser/blob/main/config.go#L28

I'm preparing the release of this tool today 🎉  so this feature will be in that release.
